# Generated by Django 5.0.6 on 2024-10-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_est_date_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='est_date_new',
        ),
    ]
