# Generated by Django 5.0.6 on 2024-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_est_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='est_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
