# Generated by Django 5.0.6 on 2024-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_applyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
