# Generated by Django 5.0.6 on 2024-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_applyjob_is_accepted_applyjob_is_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='status',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
